# Generated by Django 4.0.4 on 2022-04-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_price_product_mprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mprice',
            new_name='m_price',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=False, max_length=400),
        ),
        migrations.AddField(
            model_name='product',
            name='rent_price',
            field=models.FloatField(default=False),
        ),
    ]
